In [7]:
# Dates management
import datetime

# Visualization library
import altair as alt

# Data manipulation library
import pandas as pd

# Enable Altair to display all rows of data
alt.data_transformers.enable('default', max_rows=None)

DataTransformerRegistry.enable('default')

dataframe.to_pickle()

In [8]:

# Chargement des differets dataframes
df_person = pd.read_pickle('datap/df_person.pkl')
df_person.info()
df_person.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1547 entries, 0 to 1546
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   birth_datetime       1547 non-null   datetime64[ns]
 1   death_datetime       830 non-null    datetime64[ns]
 2   gender_source_value  1547 non-null   object
 3   cdm_source           1547 non-null   object
 4   person_id            1547 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(2)
memory usage: 60.6+ KB

  birth_datetime death_datetime gender_source_value cdm_source   person_id
0     1984-11-06            NaT                   f      EHR 1  88817330.0
1     1961-03-29     2021-06-07                   f      EHR 1  82132985.0
2     1972-08-24            NaT                   m      EHR 1  87488498.0
3     1962-12-31     2024-10-19                male      EHR 1  86280490.0
4     1948-09-30     2020-05-27              female      EHR 1  81646230.0

In [9]:
df_condition = pd.read_pickle('datap/df_condition.pkl')
df_condition.info()
df_condition.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2152 entries, 0 to 2151
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   visit_occurrence_id      2152 non-null   float64
 1   person_id                2152 non-null   float64
 2   condition_occurrence_id  2152 non-null   float64
 3   condition_source_value   2152 non-null   object
dtypes: float64(3), object(1)
memory usage: 67.4+ KB

,visit_occurrence_id,person_id,condition_occurrence_id,condition_source_value
0,85319808.0,84829170.0,87142885.0,T51
1,80902406.0,85929376.0,89378651.0,Z720
2,84295593.0,86868894.0,85796828.0,C504
3,84975826.0,85566948.0,81895083.0,F023
4,83844409.0,89203324.0,87313829.0,Z803

In [10]:
df_visit = pd.read_pickle('datap/df_visit.pkl')
df_visit.info()
df_visit.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1547 entries, 0 to 1546
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   visit_occurrence_id   1547 non-null   float64
 1   care_site_id          1547 non-null   object
 2   visit_start_datetime  1547 non-null   datetime64[ns]
 3   visit_end_datetime    1546 non-null   datetime64[ns]
 4   visit_source_value    1547 non-null   object
 5   person_id             1547 non-null   float64
dtypes: datetime64[ns](2), float64(2), object(2)
memory usage: 72.6+ KB

,visit_occurrence_id,care_site_id,visit_start_datetime,visit_end_datetime,visit_source_value,person_id
0,88801206.0,Centre F.Sinoussi,2020-01-24,2020-01-26,Hospitalisés,82723807.0
1,81327360.0,Centre F.Sinoussi,2020-02-25,2020-03-05,Hospitalisés,80260379.0
2,89802376.0,GHU A.Fleming,2022-03-26,2022-03-27,Hospitalisés,85613365.0
3,81405613.0,Centre F.Sinoussi,2024-07-06,2024-07-07,Hospitalisés,80139607.0
4,80686859.0,Hopital M.Bres,2024-12-30,2025-01-08,Hospitalisés,87634325.0

In [11]:
# Lister toutes les valeurs de l'identifiant ICR-10

df_condition.condition_source_value.value_counts()

condition_source_value
F023    276
G20     264
C19     253
C34     249
Z803    129
C500     96
I13      94
C50      93
I12      87
C502     86
C503     83
C504     74
C501     73
Z587     69
T51      41
Z720     39
K70      32
Z864     31
F10      28
E11      16
Z716     12
E12      11
I15       8
E10       8
Name: count, dtype: int64

Empty DataFrame
Columns: [visit_occurrence_id, person_id, condition_occurrence_id, condition_source_value]
Index: []

In [13]:
# Index des lignes nulles
df_visit[df_visit['visit_end_datetime'].isna()].index

Index([659], dtype='int64')

In [14]:
# on determine la ligne ou il y a des valeurs nulles pour visit end datetime
nulls = df_visit[df_visit['visit_end_datetime'].isna()]
print(nulls)

     visit_occurrence_id    care_site_id visit_start_datetime  \
659           83003531.0  Hopital M.Bres           2025-11-26

    visit_end_datetime visit_source_value   person_id
659                NaT       Hospitalisés  85156449.0

In [15]:
# exploration du dataset person
df_person.isna().sum()

birth_datetime           0
death_datetime         717
gender_source_value      0
cdm_source               0
person_id                0
dtype: int64

In [16]:

# on filtre les personnes nées avant 1910 ( outlier pour la suite de l'analyse)
df_person_fix = df_person[df_person['birth_datetime']>=pd.to_datetime("01/01/1910")]

In [17]:
birth_dates_summary = df_person_fix.groupby("birth_datetime", as_index=False).person_id.count()

In [18]:
alt.Chart(birth_dates_summary).mark_bar(size=1).encode(
    alt.X('birth_datetime:T', scale=alt.Scale(padding=5)),
    y='person_id:Q'
)

alt.Chart(...)

In [19]:
def explore(df_person):
    print("=== SHAPE ===")
    print(df_person.shape)
    
    print("\n=== TYPES ===")
    print(df_person.dtypes)
    
    print("\n=== VALEURS MANQUANTES ===")
    missing = df_person.isna().sum()
    print(missing[missing > 0])
    
    print("\n=== DOUBLONS ===")
    print(f"{df_person.duplicated().sum()} doublons")
    
    print("\n=== STATISTIQUES ===")
    print(df_person.describe(include='all'))
    
    print("\n=== APERÇU ===")
    return df_person.head()


explore(df_person)

=== SHAPE ===
(1547, 5)

=== TYPES ===
birth_datetime         datetime64[ns]
death_datetime         datetime64[ns]
gender_source_value            object
cdm_source                     object
person_id                     float64
dtype: object

=== VALEURS MANQUANTES ===
death_datetime    717
dtype: int64

=== DOUBLONS ===
0 doublons

=== STATISTIQUES ===
                       birth_datetime                 death_datetime  \
count                            1547                            830
unique                            NaN                            NaN
top                               NaN                            NaN
freq                              NaN                            NaN
mean    1969-08-10 01:32:09.153199742  2022-12-22 12:08:40.481927680
min               1850-11-23 00:00:00            2019-12-11 00:00:00
25%               1950-10-29 00:00:00            2021-06-21 06:00:00
50%               1968-07-31 00:00:00            2023-01-05 00:00:00
75%               1989-01-28 00:00:00            2024-06-16 18:00:00
max               2024-08-24 00:00:00            2025-12-18 00:00:00
std                               NaN                            NaN

       gender_source_value cdm_source     person_id
count                 1547       1547  1.547000e+03
unique                   4          1           NaN
top                 female      EHR 1           NaN
freq                   507       1547           NaN
mean                   NaN        NaN  8.506276e+07
min                    NaN        NaN  8.000614e+07
25%                    NaN        NaN  8.259066e+07
50%                    NaN        NaN  8.518543e+07
75%                    NaN        NaN  8.749158e+07
max                    NaN        NaN  8.999072e+07
std                    NaN        NaN  2.859891e+06

=== APERÇU ===

  birth_datetime death_datetime gender_source_value cdm_source   person_id
0     1984-11-06            NaT                   f      EHR 1  88817330.0
1     1961-03-29     2021-06-07                   f      EHR 1  82132985.0
2     1972-08-24            NaT                   m      EHR 1  87488498.0
3     1962-12-31     2024-10-19                male      EHR 1  86280490.0
4     1948-09-30     2020-05-27              female      EHR 1  81646230.0

In [20]:
def explore(df_condition):
    print("=== SHAPE ===")
    print(df_condition.shape)
    
    print("\n=== TYPES ===")
    print(df_condition.dtypes)
    
    print("\n=== VALEURS MANQUANTES ===")
    missing = df_condition.isna().sum()
    print(missing[missing > 0])
    
    print("\n=== DOUBLONS ===")
    print(f"{df_condition.duplicated().sum()} doublons")
    
    print("\n=== STATISTIQUES ===")
    print(df_condition.describe(include='all'))
    
    print("\n=== APERÇU ===")
    return df_condition.head()


explore(df_condition)

=== SHAPE ===
(2152, 4)

=== TYPES ===
visit_occurrence_id        float64
person_id                  float64
condition_occurrence_id    float64
condition_source_value      object
dtype: object

=== VALEURS MANQUANTES ===
Series([], dtype: int64)

=== DOUBLONS ===
0 doublons

=== STATISTIQUES ===
        visit_occurrence_id     person_id  condition_occurrence_id  \
count          2.152000e+03  2.152000e+03             2.152000e+03
unique                  NaN           NaN                      NaN
top                     NaN           NaN                      NaN
freq                    NaN           NaN                      NaN
mean           8.494005e+07  8.502724e+07             8.498605e+07
std            2.924759e+06  2.859464e+06             2.882781e+06
min            8.000604e+07  8.000614e+07             8.000599e+07
25%            8.248018e+07  8.252643e+07             8.250818e+07
50%            8.484356e+07  8.515409e+07             8.491354e+07
75%            8.752894e+07  8.748837e+07             8.749037e+07
max            8.999485e+07  8.999072e+07             8.998755e+07

       condition_source_value
count                    2152
unique                     24
top                      F023
freq                      276
mean                      NaN
std                       NaN
min                       NaN
25%                       NaN
50%                       NaN
75%                       NaN
max                       NaN

=== APERÇU ===

,visit_occurrence_id,person_id,condition_occurrence_id,condition_source_value
0,85319808.0,84829170.0,87142885.0,T51
1,80902406.0,85929376.0,89378651.0,Z720
2,84295593.0,86868894.0,85796828.0,C504
3,84975826.0,85566948.0,81895083.0,F023
4,83844409.0,89203324.0,87313829.0,Z803

In [21]:
def explore(df_visit):
    print("=== SHAPE ===")
    print(df_visit.shape)
    
    print("\n=== TYPES ===")
    print(df_visit.dtypes)
    
    print("\n=== VALEURS MANQUANTES ===")
    missing = df_visit.isna().sum()
    print(missing[missing > 0])
    
    print("\n=== DOUBLONS ===")
    print(f"{df_visit.duplicated().sum()} doublons")
    
    print("\n=== STATISTIQUES ===")
    print(df_visit.describe(include='all'))
    
    print("\n=== APERÇU ===")
    return df_visit.head()


explore(df_visit)

=== SHAPE ===
(1547, 6)

=== TYPES ===
visit_occurrence_id            float64
care_site_id                    object
visit_start_datetime    datetime64[ns]
visit_end_datetime      datetime64[ns]
visit_source_value              object
person_id                      float64
dtype: object

=== VALEURS MANQUANTES ===
visit_end_datetime    1
dtype: int64

=== DOUBLONS ===
0 doublons

=== STATISTIQUES ===
        visit_occurrence_id       care_site_id           visit_start_datetime  \
count          1.547000e+03               1547                           1547
unique                  NaN                  4                            NaN
top                     NaN  Centre F.Sinoussi                            NaN
freq                    NaN                425                            NaN
mean           8.496008e+07                NaN  2022-12-22 00:37:14.001293056
min            8.000604e+07                NaN            2019-12-02 00:00:00
25%            8.248496e+07                NaN            2021-06-17 00:00:00
50%            8.487582e+07                NaN            2022-12-22 00:00:00
75%            8.752173e+07                NaN            2024-07-08 12:00:00
max            8.999485e+07                NaN            2025-11-29 00:00:00
std            2.909357e+06                NaN                            NaN

                   visit_end_datetime visit_source_value     person_id
count                            1546               1547  1.547000e+03
unique                            NaN                  1           NaN
top                               NaN       Hospitalisés           NaN
freq                              NaN               1547           NaN
mean    2022-12-28 23:54:24.683053056                NaN  8.506276e+07
min               2019-12-11 00:00:00                NaN  8.000614e+07
25%               2021-06-22 18:00:00                NaN  8.259066e+07
50%               2023-01-03 00:00:00                NaN  8.518543e+07
75%               2024-07-13 18:00:00                NaN  8.749158e+07
max               2025-12-18 00:00:00                NaN  8.999072e+07
std                               NaN                NaN  2.859891e+06

=== APERÇU ===

,visit_occurrence_id,care_site_id,visit_start_datetime,visit_end_datetime,visit_source_value,person_id
0,88801206.0,Centre F.Sinoussi,2020-01-24,2020-01-26,Hospitalisés,82723807.0
1,81327360.0,Centre F.Sinoussi,2020-02-25,2020-03-05,Hospitalisés,80260379.0
2,89802376.0,GHU A.Fleming,2022-03-26,2022-03-27,Hospitalisés,85613365.0
3,81405613.0,Centre F.Sinoussi,2024-07-06,2024-07-07,Hospitalisés,80139607.0
4,80686859.0,Hopital M.Bres,2024-12-30,2025-01-08,Hospitalisés,87634325.0